---
- name: Configure UFW based on node requirements
  hosts: "{{ target_hosts }}"
  become: yes
  tasks:
    - name: Allow OpenSSH (IPv4 and IPv6)
      community.general.ufw:
        rule: allow
        name: OpenSSH
    - name: Allow specific internal cluster ports from 10.0.0.0/24
      community.general.ufw:
        rule: allow
        src: '10.0.0.0/24'
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      loop:
        - { port: '6400', proto: 'tcp' }
        - { port: '6443', proto: 'tcp' }
        - { port: '4240', proto: 'tcp' }
        - { port: '8472', proto: 'udp' }
    - name: Enable UFW
      community.general.ufw:
        state: enabled
